<?php

namespace App\Http\Controllers\User;

use App\Http\Controllers\Base\BaseController;
use App\Models\DessertStation;
use Illuminate\Http\Request;

class DessertStationController extends BaseController
{
    public function index()
    {
        $data = DessertStation::all()->where('user_id',auth()->id());
        return response()->json([
            'status' => 200,
            'message' => 'Success',
            'success' => true,
            'data' => $data,
        ]);
    }
    public function show($id)
    {
        $model = DessertStation::class;
        return parent::showBase($id, $model); // TODO: Change the autogenerated stub
    }

    public function store(Request $request)
    {
        $model = DessertStation::class;
        $params = $request->all();
        $params['user_id'] = auth()->id();
        $rules = [
            'name'=>'required|string|min:3|max:100',
            'phase'=>'required|numeric|min:1',
        ];
        return parent::storeBase($model, $params, $rules); // TODO: Change the autogenerated stub
    }
    public function update($id)
    {
        $model = DessertStation::class;
        $params = \request()->all();
        $params['user_id'] = auth()->id();
        $rules = [
            'name'=>'required|string|min:3|max:100',
            'phase'=>'required|numeric|min:1',
        ];
        return parent::updateBase($id, $model, $params, $rules); // TODO: Change the autogenerated stub
    }
    public function destroy($id)
    {
        $model = DessertStation::class;
        return parent::destroyBase($id, $model); // TODO: Change the autogenerated stub
    }
}
