<?php

namespace App\Http\Controllers\User;

use App\Http\Controllers\Base\BaseController;
use App\Models\DessertStation;
use App\Models\UpdatePhase;
use Illuminate\Http\Request;

class UpdatePhaseController extends BaseController
{
    public function index($id)
    {
        $station = DessertStation::query()->where('id', $id)->where('user_id', auth()->id())->first();

        if (!$station) {
            return response()->json([
                'status' => 404,
                'message' => 'Dessert station not found for the authenticated user.',
                'success' => false
            ], 404);
        }

        $data = UpdatePhase::where('station_id', $station->id)->get();

        if ($data->isEmpty()) {
            return response()->json([
                'status' => 404,
                'message' => 'No update phases found for the dessert station.',
                'success' => false
            ], 404);
        }

        return response()->json([
            'status' => 200,
            'message' => 'Success',
            'success' => true,
            'data' => $data
        ]);

    }
    public function show($id)
    {
        $model = UpdatePhase::class;
        $updateSt = UpdatePhase::query()->find($id);

        if (!$updateSt) {
            return response()->json([
                'status' => 404,
                'message' => 'Update phase not found.',
                'success' => false
            ], 404);
        }

        $station = DessertStation::query()
            ->where('id', $updateSt->station_id)
            ->where('user_id', auth()->id())
            ->first();

        if (!$station) {
            return response()->json([
                'status' => 403,
                'message' => 'You are not authorized to view this update phase.',
                'success' => false
            ], 403);
        }

        return parent::showBase($id, $model);
    }
    public function store(Request $request)
    {
        $model = UpdatePhase::class;
        $params = $request->all();
        $rules = [
            'last_date'=>'required|date',
            'time'=>'required|numeric|min:1',
            'next_date'=>'required|date',
            'station_id'=>'required|exists:dessert_stations,id'
        ];
        $station = DessertStation::query()->where('id',$request->station_id)->where('user_id', auth()->id())->first();
        if ($station){
            return parent::storeBase($model, $params, $rules); // TODO: Change the autogenerated stub
        }else{
            return response()->json([
                'status' => 403,
                'message' => 'You are not authorized to view this update phase.',
                'success' => false
            ], 403);
        }

    }
    public function update($id)
    {
        $model = UpdatePhase::class;
        $params = \request()->all();
        $updateSt = UpdatePhase::query()->where('id',$id)->first();
        if ($updateSt){
            $station = DessertStation::query()->where('id',$params['station_id'])->where('user_id', auth()->id())->first();
            if ($station){
                $params['user_id'] = auth()->id();
                $rules = [
                    'last_date'=>'required|date',
                    'time'=>'required|numeric|min:1',
                    'next_date'=>'required|date',
                    'station_id'=>'required|exists:dessert_stations,id'
                ];
                return parent::updateBase($id, $model, $params, $rules); // TODO: Change the autogenerated stub
            }else{
                return response()->json([
                    'status' => 403,
                    'message' => 'You are not authorized to view this update phase.',
                    'success' => false
                ], 403);
            }
        }else{
            return response()->json([
                'status' => 404,
                'message' => 'Update phase not found.',
                'success' => false
            ], 404);
        }

    }
    public function destroy($id)
    {
        $model = UpdatePhase::class;
        $updateSt = UpdatePhase::query()->where('id',$id)->first();
        if ($updateSt){
            $station = DessertStation::query()->where('id',$updateSt->station_id)->where('user_id', auth()->id())->first();
            if ($station){
                return parent::destroyBase($id, $model); // TODO: Change the autogenerated stub
            }else{
                return response()->json([
                    'status' => 403,
                    'message' => 'You are not authorized to view this update phase.',
                    'success' => false
                ], 403);
            }
        }else{
            return response()->json([
                'status' => 404,
                'message' => 'Update phase not found.',
                'success' => false
            ], 404);
        }


    }
}
